version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: ec2-user
        uid: 1000
    image: intern-php
    container_name: intern-php-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: intern-php-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"
